### ISSUE TITLE
"Paging" is not available in Windows 10 Photos

### ISSUE THREAD

**Issue by camstevenson** [winfsp/winfsp#238]
## Bug Report

The Windows 10 Photos app, when launched with an image in a folder of images, provides next and previous arrows (shown on mouseover) to allow navigation to the next and previous image in the folder.

These arrows (and in fact, the paging itself) are not available when the image is located in a folder of images on a WinFSP drive.

### How to Reproduce

Using memfs, create a folder containing any number of images.  Launch Windows 10 Photos on an image in the folder.  Arrow indicators are not displayed on mouseover to the left or right of the displayed image, nor can arrow keys be used to navigate to the next or previous image in the folder.

### Behaviors

Expected: the ability to navigate within Windows 10 Photos to the next or previous image in the folder
Actual: No navigation available

### Environment

- OS version and build: Windows 10 17763.557 (1809)
- WinFsp version and build: 1.4.19049

**Comment by billziss-gh** [comment]
Does this happen when you start memfs as a disk or network file system?

**Comment by camstevenson** [comment]
It's mounted as a disk.

Cheers,

Cam

**Comment by billziss-gh** [comment]
I believe I have addressed this issue in commit cf13cac43813c41f66e34d27155d25c90f795b7c.

Unfortunately I am not certain when I will be making a new release with this fix.

**Comment by billziss-gh** [comment]
This fix is included in the upcoming release WinFsp 2022+ARM64 Beta2.
