### ISSUE TITLE
Can't run regedit.exe from the mounted volume

### ISSUE THREAD

**Issue by jumbo-ilct** [winfsp/winfsp#355]
## Bug Report

Can't run regedit.exe from the mounted volume. 

### How to Reproduce

1. The volume is mounted by "memfs-x64 -m z:".
2. Run "cmd"
3. type "Z:"
4. type "regedit"

And it failed, windows said can't access c:\windows\regedit.exe

![image](https://user-images.githubusercontent.com/6507322/110900525-d2ee2c00-833d-11eb-8194-a6e7eb40e508.png)

But when I mounted a directory by command line "memfs-x64 -m c:\md", and run "regedit" in directory "c:\md", the regedit.exe started successfully.

### Environment

- OS version: windows 10
- WinFsp version and build: 1.9.21070.0

**Comment by billziss-gh** [comment]
I will look into this more closely, but I believe the reason for this problem is a combination of the following:

- The drive Z: is created in the namespace of the local user.
- Regedit is an application requiring elevation and elevated processes cannot access local drives.

**Comment by billziss-gh** [comment]
I can confirm the problem when mounting as a disk file system. However it seems to work correctly when mounting as a network file system (using the `-u` switch).

I have the following test matrix:

| Context  | Command line | Comment | Works |
| :-- | :-- | :-- | :-: |
| User | `memfs-x64 -m Z:`  | Local disk | :x:
| Elevated | `memfs-x64 -m \\.\Z`  | Global disk via Mount Manager | :x:
| LocalSystem | `memfs-x64 -m Z:` | Global disk via LocalSystem | :x:
| * | `memfs-x64 -m Z: -u \memfs\share` | Network file system | :heavy_check_mark:

**Comment by billziss-gh** [comment]
I have looked into this again. It appears that memfs works correctly when it advertises that the file system is NTFS (using the `-F NTFS` option).

In the image below notice that when running with `-F NTFS` the `regedit.exe` invocation succeeds.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/15330948/194543009-a68ddc4f-a010-4468-877e-22d0b35502bc.png">
