### ISSUE TITLE
FUSE: AzureAD accounts (SID 1-12-1-) are not currently supported

### ISSUE THREAD

**Issue by infeo** [winfsp/winfsp#387]
## Bug Report

Logged in with an Azure AD account, a filesystem mounted over the native fuse Windows API to a drive letter allows only read-only access. Looking at the permissions, the owner the SID S-1-0-65534 is set instead of the logged in SID (S-1-12-X). 
Using the `uid` fuse option does not change this. Mounting to a directory works fine.

Output of fsptool...
* probing the drive letter
```
&.\bin\fsptool-x64.exe perm E:\
O:S-1-5-0G:S-1-5-0D:P(A;;FA;;;S-1-5-0)(A;;0x1201ef;;;S-1-5-0)(A;;0x1201ef;;;WD) (perm=0:0:0777)
```
* probing the reparse point
```
PS C:\Program Files (x86)\WinFsp> &.\bin\fsptool-x64.exe perm D:\mnt
O:S-1-12-1-3430994482-1138470567-3993656486-XXXG:S-1-12-1-3430994482-1138470567-3993656486-XXXD:(A;ID;FA;;;BA)(A;OICIIOID;GA;;;BA)(A;ID;FA;;;SY)(A;OICIIOID;GA;;;SY)(A;ID;0x1301bf;;;AU)(A;OICIIOID;SDGXGWGR;;;AU)(A;ID;0x1200a9;;;BU)(A;OICIIOID;GXGR;;;BU) (perm=3163147857:3163147857:0777)
```
### How to Reproduce

1. Log in with an Azure AD account. 
2. Mount your filesystem (e.g. memfs-fuse) to a free drive letter
3. Check the permissions

### Behaviors

**Expected:**  As owner the currently logged in user is set and has write access.
**Actual:** The SID S-1-0-65534 is set as owner and noone has write access.

### Environment

- OS version and build: 10 Pro,  Build 19042.1165
- WinFsp version and build: 2021.1 Beta2

**Comment by billziss-gh** [comment]
Apologies for the late response. Have you tried mounting the file system with the `-ouid=-1` flag?

**Comment by infeo** [comment]
Thanks, but I also forgot about the issue^^

> Have you tried mounting the file system with the -ouid=-1 flag?

Yes. The problem occurs with memfs-fuse and memfs-fuse3, both mounted with uid=-1. If that matters, the reg key `DistinctPermsForSameOwnerGroup` was set to 1.

**Comment by billziss-gh** [comment]
The usual problem with such accounts is that the user and group are the same. The standard solutions are:

- Set gid explicitly using `-o gid=GID`. I looked at the parent issue (cryptomator/cryptomator#1421) and see that you already tried this (with `-o gid=11`).

- Set `DistinctPermsForSameOwnerGroup` to 1. You also tried this. (I assume with latest WinFsp as previous versions did not support this setting -- please confirm.)

Based on this it is likely this is a different issue. But to confirm please run the following commands for me and report the output:

- `fsptool id`. Report the output.

- `fsptool perm .\FILENAME` with `FILENAME` the name of a file inside the mount. (Of course if you are testing against memfs you may not be able to create a file.)

Some suggestions:

- Try running with an explicit `-o umask=777`.

- Try running with an explicit `-o create_umask=777` (or the alternatives `create_file_umask` and `create_dir_umask`).

- Does this happen if you mount as a network drive (by using a flag such as `-o VolumePrefix=/myfs/test`)?

Ideally I would like to repro this myself. Is there an easy way to test this with an Azure AD account?

**Comment by billziss-gh** [comment]
It may also be that WinFsp-FUSE cannot correctly map Azure ID SID's to UID's.

Possibly related issues:

- https://github.com/billziss-gh/winfsp/issues/199#issuecomment-485137491
- https://github.com/billziss-gh/winfsp/issues/381

**Comment by infeo** [comment]
> I assume with latest WinFsp as previous versions did not support this setting -- please confirm

Yes, using the latest stable release: https://github.com/billziss-gh/winfsp/releases/tag/v1.10

Running your `fsptool id` yields:
```
PS C:\Program Files (x86)\WinFsp\bin> .\fsptool-x64.exe id
User=S-1-12-1-3430994482-1138470567-3993656486-3163079249(AzureAD\SomeUser) (uid=3163147857)
Owner=S-1-12-1-3430994482-1138470567-3993656486-3163079249(AzureAD\SomeUser) (uid=3163147857)
Group=S-1-12-1-3430994482-1138470567-3993656486-3163079249(AzureAD\SomeUser) (gid=3163147857)
```

I used `fsptool perm` in combination with memfs-fuse, because it was always possible to create files via powershell & `New-Item`. The option `-o uid=-1` was always set.
If `gid=-1`or non options where used, the output was:
```
PS C:\Program Files (x86)\WinFsp\bin> .\fsptool-x64.exe perm X:\test.txt
O:S-1-0-65534G:S-1-0-65534D:P(A;;0x1f01bf;;;S-1-0-65534)(A;;0x1201af;;;S-1-0-65534)(A;;0x120088;;;WD) (perm=65534:65534:0770)
```

If `gid=11`, the output was:
```
PS C:\Program Files (x86)\WinFsp\bin> .\fsptool-x64.exe perm X:\test.txt
O:S-1-0-65534G:AUD:P(A;;0x1f01bf;;;S-1-0-65534)(A;;0x1201af;;;AU)(A;;0x120088;;;WD) (perm=65534:11:0777)
```

But whatever the options, from the explorer one was never able to create files. Some additional testing showed that with some options i was able to copy empty files into the mounted fs, sometimes i was not able to copy empty files inside to somewhere else... all in all a mixed picture 😅

**Comment by infeo** [comment]
I'll test the network provider suggestion later. Also the hint with changes in the mapping are worth investigating.

Regarding an azure ad test account, yes, this is possible, see https://azure.microsoft.com/en-us/free/. I honestly don't know the effort to set it up, you might find some helpful info on [reddit](https://www.reddit.com/r/AZURE/comments/aw1nqq/azure_ad_test_environment_where_to_start_and_what/).

**Comment by billziss-gh** [comment]
@infeo thank you for the posted output and for including the full SID; it was useful in understanding the problem.

The mapping of the SID to UID in your output is:

```
S-1-12-1-3430994482-1138470567-3993656486-3163079249 -> 3163147857
```

Looking at the function [`FspPosixMapSidToUid` in file `posix.c`](https://github.com/billziss-gh/winfsp/blob/v1.10/src/shared/ku/posix.c#L673-L679) we find that it does not directly recognize SIDs that start with `S-1-12-` and instead falls back into a general case:

```C
    {
        /* [IDMAP]
         * Other well-known SIDs:
         *     S-1-X-Y                             <=> uid/gid: 0x10000 + 0x100 * X + Y
         */
        *PUid = 0x10000 + 0x100 * Authority + Rid;
    }
```

Indeed if I substitute `Authority=12` and `Rid=3163079249` I will get a UID of `3163147857`.

Unfortunately the function [`FspPosixMapUidToSid` in file `posix.c`](https://github.com/billziss-gh/winfsp/blob/v1.10/src/shared/ku/posix.c#L435) (which is the inverse of `FspPosixMapSidToUid`) is not able to invert this UID back to the original SID and instead it responds with the "unmapped" SID `S-1-0-65534`.

The mapping between SIDs and UIDs is supposed to be bijective, otherwise things will not work very well (as you are finding out).

----

The mapping between SID's and UID's is based on a mapping that a Microsoft product (Services For Unix) used to do. This (now discontinued) product specified a mapping between various kinds of SIDs, but never a mapping for SIDs that have the form of `S-1-12-` (likely because they did not exist back then).

I know that Cygwin is using a similar scheme for mapping SIDs to UIDs. I will check to see if they have solved the problem of `S-1-12-` SIDs and how they did it. If Cygwin has not solved this problem, then we may have to invent our own mapping.

**Comment by billziss-gh** [comment]
Found this Cygwin commit that looks relevant: https://github.com/cygwin/cygwin/commit/eb61113daf84bea95b81551b4c3826d4574c5688

**Comment by billziss-gh** [comment]
@infeo 

I have done some research on Azure AD SID's and they seem to have the format `S-1-12-1-www-xxx-yyy-zzz` where `www-xxx-yyy-zzz` is derived from the "Object ID" of the Azure account in question. The Object ID itself appears to be a GUID (16 bytes) and it is easy to transform between `S-1-12-1-` SID's and Object ID's. (See for example: https://oliverkieselbach.com/2020/05/13/powershell-helpers-to-convert-azure-ad-object-ids-and-sids/)

Unfortunately this means that it is not possible to create a bijective mapping between SID's and 
Unfortunately this means that it is not straightforward to

**Comment by infeo** [comment]
I think this would be a viable option for now to solve the issue. Maybe winfsp can even provide some kind of default (for example involving hasing the SID) with `-o uidmap=-1` (of course the options has to specified nonetheless)? With this, consumers of this library can easily continue using it and if problems arise, they can decide to use a custom mapping.

@overheadhunter Do you have some thoughts about this?

**Comment by billziss-gh** [comment]
Commits 74bb51ae07e9ac341e5010fb16459b19daba5aab and 9ae9b8ff2cf694ac45b12c5176bf8136388e6575 add `uidmap` and AzureAD support.

I have made it so the `-o uid=-1` option now detects an AzureAD account and maps it to uid 4096 (for Cygwin compatibility).

Please note that while I have tested the new `uidmap` option, I do not have AzureAD and I am not able to fully test the AzureAD support.

**Comment by billziss-gh** [comment]
@infeo please let me know if this issue is resolved with latest WinFsp (2022+ARM64 Beta3).

https://github.com/winfsp/winfsp/releases
