### ISSUE TITLE
Unable to open image file using Windows 10 default web viewer

### ISSUE THREAD

**Issue by chaltteog** [winfsp/winfsp#395]
## Bug Report

Unable to open image file using Windows 10 default web viewer in network mode

### How to Reproduce

1.  Connect WINFSP network mode
2.  Open Image file using Windows default web viewer
![image](https://user-images.githubusercontent.com/44234134/136166047-4f6654c6-5999-4e21-80fd-65db5e04eff5.png)

### Behaviors

I want to open the image file using windows 10 default app viewer

### Environment

- OS version and build: Windows 10 Pro 20H2(OS Build : 19042.1237)
- WinFsp version and build: v1.10B2

**Comment by pstratton** [comment]
I'm having this issue as well. I can see the image if I "Edit with Photos" or use a different viewer.

**Comment by billziss-gh** [comment]
Which file system are you experiencing this problem with?

**Comment by pstratton** [comment]
I'm using Windows 10 and was just getting ready to submit another ticket as
well, commenting on
https://github.com/billziss-gh/winfsp/issues/376#issue-938997033. I can no
longer mount or open previously mounted drives. Trying to open previously
mounted drives I get the WFSP: network not present or not started, and I
cannot get past the enter credentials when trying to mount new drives.

I only mention this as I can't open anything to help test this
issue further.
[image: image.png]
Best,
    Phil

**Comment by billziss-gh** [comment]
I am wondering if your installation is corrupted somehow if you are having multiple issues.

Can you please let me know which file system you are experiencing this issue with? Is it MEMFS? Passthrough? SSHFS-Win? Something else?

**Comment by pstratton** [comment]
I'm using SSHFS-Win. I'm not sure what changed, but it's working on and off now. I had to restart the winpfs.launcher service a couple of times. It indicated it was running but looking at the properties showed it as stopped.

**Comment by billziss-gh** [comment]
Not sure about the image file problem as I have not seen it in SSHFS-Win.

However regarding the problem with mounting an SSHFS-Win drive: there was indeed a bug that was fixed in the latest WinFsp Betas. I recommend downloading and using WinFsp 2022 Beta4 or later ([link](https://github.com/billziss-gh/winfsp/releases)), which has a fix for this problem.

**Comment by billziss-gh** [comment]
I believe I have addressed the issue described in the OP in commit cf13cac43813c41f66e34d27155d25c90f795b7c.

Unfortunately I am not certain when I will be making a new release with this fix.

**Comment by billziss-gh** [comment]
This fix is included in the upcoming release WinFsp 2022+ARM64 Beta2.
