### ISSUE TITLE
Visual Studio C++ project building on the mapped drive

### ISSUE THREAD

**Issue by W3LLD0NE** [winfsp/winfsp#419]
## Bug Report

I use Cryptomator 1.6.8 + it's built-in version of WinFsp.
What I wanted to do is to place my Visual Studio's C++ projects into the vault (mapped as WinFsp/FUSE drive) and build from there.
The problem is that Visual Studio can't work properly with files located on FUSE file system, and as result can't properly build the binaries.
Not sure whether it's a bug/limitation of WinFsp or Visual Studio/MSVC (filed them feedback too).

### How to Reproduce

1. [Optional] Download & install Cryptomator: https://cryptomator.org/downloads/
2. [Optional] Open it up, go to settings -> Virtual drive and choose ‘FUSE’. Restart the program.
3. [Optional] Create a new vault with any password and map it to the system (not sure how the mapping options are translated internally but in Cryptomator they are "-ouid=-1 -ogid=11 -ovolname=Programming" which is default).
4. Create a new C++ console project on that mapped drive and try to compile.

### Behaviors

-Expected a working compilation process, properly built binaries and non-corrupted VS solution database.
-Actually receiving either empty zero-byte binaries/solution database files or an error accessing them.

### Environment

- OS version and build: 19044.1645
- WinFsp version and build: 1.10.22006
- Visual Studio version: 17.1.4

**Comment by billziss-gh** [comment]
WinFsp file systems can work properly with Visual Studio. You can confirm this by using the MEMFS or NTPTFS file systems. (The WinFsp project in general only accepts bugs demonstrated against those two file systems.)

The problem likely lies with Cryptomator’s implementation. A common problem with FUSE file systems that don’t work with Visual Studio is that they do not report a proper inode number (`st_ino`) in `getattr`. I have found that without proper inode numbers, Visual Studio builds fail in unexpected ways.

**Comment by W3LLD0NE** [comment]
> WinFsp file systems can work properly with Visual Studio. You can confirm this by using the MEMFS or NTPTFS file systems. (The WinFsp project in general only accepts bugs demonstrated against those two file systems.)
> 
> The problem likely lies with Cryptomator’s implementation. A common problem with FUSE file systems that don’t work with Visual Studio is that they do not report a proper inode number (`st_ino`) in `getattr`. I have found that without proper inode numbers, Visual Studio builds fail in unexpected ways.

thanks, my bad then, gonna create issue for Cryptomator.
