### ISSUE TITLE
is it safe to remove VolumeParams.AlwaysUseDoubleBuffering in driver.h

### ISSUE THREAD

**Issue by fxinren** [winfsp/winfsp#421]
in driver.h
BOOLEAN FspReadIrpShouldUseProcessBuffer(PIRP Irp, SIZE_T BufferSize)
{
    ASSERT(0 != Irp);
#if DBG
    return DEBUGTEST(50) ||
#else
    return FspProcessBufferSizeMax >= BufferSize ||
#endif
        FspFsvolDeviceExtension(IoGetCurrentIrpStackLocation(Irp)->DeviceObject)->
            VolumeParams.AlwaysUseDoubleBuffering; // is it safe to remove?
}

the variable "VolumeParams.AlwaysUseDoubleBuffering" is set to 1, so function "FspReadIrpShouldUseProcessBuffer() " in read.c will always turn true, and the "else" chunk would be never reachable.

in another discussion about READ/WRITE buffers , https://groups.google.com/g/winfsp/c/1p49hsoqGqo/m/2E8Ri8_JAgAJ, it was said as following:
- Due to a limitation of how Windows maps buffers into 2 address spaces there was a possibility to use WinFsp to crash Windows (in pre-v1.0 WinFsp versions) in some situations. (I.e. a malicious app that did not play by the “rules” could abuse WinFsp to do so – this is not possible in v1.0+ versions of WinFsp.)

does it mean "setting VolumeParams.AlwaysUseDoubleBuffering to 0"  would have no harm to winfsp.sys, with a the latest version of winfsp? and none of the  malicious app could use winfsp to crash Windows any more?

thanks!

**Comment by billziss-gh** [comment]
Unfortunately it is not safe to remove the `AlwaysUseDoubleBuffering` check for read IRP's. For the full reasons see #55.
