### ISSUE TITLE
`FspPosixMapPermissionsToSecurityDescriptor()` should return the size of security descriptor

### ISSUE THREAD

**Issue by hgoldfish** [winfsp/winfsp#422]
## Enhancement Request

I am implementing the `GetSecurityByName()` of `FSP_FILE_SYSTEM_INTERFACE`. This function accepts two parameters `PSECURITY_DESCRIPTOR pSecurityDescriptor` and `SIZE_T *pSecurityDescriptorSize`. If the `pSecurityDescriptorSize` is smaller than the actual size of `pSecurityDescriptor`, we return the `STATUS_BUFFER_OVERFLOW` error code.

The value of `pSecurityDescriptor` is caculated using `FspPosixMapPermissionsToSecurityDescriptor()` on the fly. The problem is that it does not return the size of the mapped security descriptor,  and I don't know how many size should copy to `pSecurityDescriptor`.

Could you append a new out parameter `SecurityDescriptorSize` to the `FspPosixMapPermissionsToSecurityDescriptor()`? The sign of function:

    FSP_API NTSTATUS FspPosixMapPermissionsToSecurityDescriptor(UINT32 Uid, UINT32 Gid, UINT32 Mode,
                   PSECURITY_DESCRIPTOR *PSecurityDescriptor);

should change to:

    FSP_API NTSTATUS FspPosixMapPermissionsToSecurityDescriptor(UINT32 Uid, UINT32 Gid, UINT32 Mode,
                   PSECURITY_DESCRIPTOR *PSecurityDescriptor, ULONG *SecurityDescriptorSize);

**Comment by billziss-gh** [comment]
Use the [`GetSecurityDescriptorLength`](https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-getsecuritydescriptorlength) API to get the security descriptor length.
