### ISSUE TITLE
Sign more installed artifacts

### ISSUE THREAD

**Issue by infeo** [winfsp/winfsp#423]
## Enhancement Request

Inspecting the installed files, one notices that only the system driver has a digital signature, while the dlls and exectubles are not signed. It not only would be nice to have those signed too, but also would increase security and trust into winfsp 😉 

I know, the installer is already signed, but it would ensure, that even after installation the files are not modified.

**Comment by billziss-gh** [comment]
This is a good idea.

Please note that currently only the driver carries a Microsoft signature. The installer (and in the future possibly the DLL's, etc.) would continue to carry my own signature.

**Comment by billziss-gh** [comment]
Closed in 9c1a7fb40babfadf0ec49a9bbe8f1fc2e168ec78.
