### ISSUE TITLE
Problem with FUSE and OneNote.

### ISSUE THREAD

**Issue by bvazx** [winfsp/winfsp#429]
## Bug Report
When I use FUSE for Cryptomator and a notebook, which is stored in the virtual drive (vault), after a certain time, OneNote is closed for no reason.

### How to Reproduce
Create a new notebook for OneNote in the virtual drive (vault).
Work in the created notebook.

### Behaviors
OneNote should not close.
But, after a certain time, OneNote is closed for no reason.
I think it happens when recording to the virtual drive (vault).
When I use Dokany 1.5.1 or WebDAV, it doesn’t happen.

### Environment
Operating System: Windows 11 Pro
Cryptomator: 1.6.10
WinFSP: 1.10.22006
Microsoft 365: OneNote

**Comment by billziss-gh** [comment]
Please report this problem to Cryptomator.

The WinFsp project can only accept bugs that can be demonstrated against its reference file systems (currently MEMFS and NTPTFS). It is not possible to troubleshoot problems with other file systems that use WinFsp.
