### ISSUE TITLE
google kubernetes (GKE) windows pods

### ISSUE THREAD

**Issue by chaimmintz** [winfsp/winfsp#438]
Anyone have any luck getting WinFSP working on GKE windows pods? I found https://winfsp.dev/doc/WinFsp-Container-Support/ that talks about container support but I am unable to get it working on GKE.

Even if I RDP into the pod and install winfsp and run "sc.exe start winfsp" (which makes the node unresponsive for a few minutes and i'm not even sure started anything) it doesn't work. The only winfsp service I see running is `WinFSP.Launcher`, not sure if that is the real service that needs to be running or something else.

When I call winfsp `fuse_main_real` method it returns 1 and doesn't emit any errors anywhere so I don't know what the problem was.

How can I get it working or at least diagnose further?

**Comment by billziss-gh** [comment]
The WinFsp container support is intended only to run user mode file systems within a container.

For this to work WinFsp must be already installed on the host computer. Then you can start the FSD (e.g. by using `sc.exe start winfsp` from the host (i.e. outside any container). It is not possible to start the FSD (which is a kernel mode driver) from inside a container.

So unfortunately your scenario will not work.

**Comment by chaimmintz** [comment]
I am able to get to the GKE host computer to install the .msi but afterwards when I run `sc.exe start winfsp` it causes the machine to blow up and reboot. Any idea why that would be? What can I look at to diagnose further?

**Comment by billziss-gh** [comment]
I am not familiar with GKE.

If you are running inside a container you will not be able to start a kernel driver. At the same time you should not be able to crash the kernel from inside a container, so I am not sure what is going on there.

**Comment by chaimmintz** [comment]
I emailed you the minidumps privately (i am unable to post them publicly)

**Comment by billziss-gh** [comment]
I have had the chance to look into this and the problems does look related to WinFsp.

Unfortunately I failed to upload to the symbol server the debugging symbols for the latest beta, so it is not really possible for me to troubleshoot this at the moment.

**Comment by billziss-gh** [comment]
I have had the chance into the new minidump and have identified the problem. I will be fixing this problem in the future.

**Comment by billziss-gh** [comment]
Commit a3765d6360b61925e99c3390723056a6746e2000 fixes this problem. I have also added some Docker testing in the automated test suite so that problems like this should not happen again.
