### ISSUE TITLE
stopped working for no reasons

### ISSUE THREAD

**Issue by 100doses** [winfsp/winfsp#444]
![Sans titre](https://user-images.githubusercontent.com/95159500/190459478-6c6af582-319d-4b65-8027-b6963875804b.png)
diag.bat output:
[diag.log](https://github.com/winfsp/winfsp/files/9577306/diag.log)

**Comment by 100doses** [comment]
btw what i tried:
- reinstall both sshfs + winfsp
- reboot
- repair with install tool
- restarting the service

**Comment by billziss-gh** [comment]
You have a very old version of WinFsp. I recommend uninstalling it and installing the latest version.

**Comment by 100doses** [comment]
I installed the latest version i found in the releases section, weird.

**Comment by 100doses** [comment]
> You have a very old version of WinFsp. I recommend uninstalling it and installing the latest version.

fixed
