### ISSUE TITLE
FUSE api on non-English Windows system has path issue

### ISSUE THREAD

**Issue by kice** [winfsp/winfsp#459]
## Bug Report

Path string encoding is not correct

### How to Reproduce

Run `passthrough-fuse3` on non English Windows system

### Behaviors

Excepted convert path from fuse api call to local codepage, but got invalid string.

File explorer does not display file name correctly or cannot open files with non ASCII characters either.

![image](https://user-images.githubusercontent.com/3945950/197341454-a34ea127-06b0-4ee5-8cfa-6fd7ad33887f.png)

### Environment

- OS version and build: Win 10.0.19043.1566
- WinFsp version and build: 1.11.22176

**Comment by billziss-gh** [comment]
Apologies for the very late response? Do you still experience this issue with the latest WinFsp 2023 beta? There has recently been some work to better support non-English systems.
