### ISSUE TITLE
Driver signing issue on Windows 7

### ISSUE THREAD

**Issue by Hub-O-Gits** [winfsp/winfsp#471]
WinFsp v1.12.22301 (2022.2)
Windows 7 x64 SP1 (still supported by MS, via ESU)

At the end of the WinFsp installation, the driver fails to install (see below.) The WinFsp FAQ touches on the issue, saying "Your Windows 7 OS is missing SHA-2 Code Signing Support." But that's not the case here, as my system is fully up to date and includes all applicable patches. 

![image](https://user-images.githubusercontent.com/29762558/203889297-cfb209c5-ffb0-410e-b973-d870ec9bda79.png)

Winfsp-x64.sys appears to have a SHA1 signature for some reason (see below.) My understanding is that MS no longer permits **_any_** inclusion of SHA1, regardless of other sigs.

![image](https://user-images.githubusercontent.com/29762558/203889332-07c7d3b6-e073-4ed5-90b2-1c69d9d9b4a9.png)

**Comment by billziss-gh** [comment]
Do you have this security update installed?

https://www.microsoft.com/en-us/download/details.aspx?id=46148

More details here:

https://learn.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929

**Comment by Hub-O-Gits** [comment]
Yes; it's installed. Like I said, my system is fully up to date. Before posting here, I checked my system for every Windows patch relating to SHA2. And in the case of KB3033929, I decided to try installing it anyway, but it erred out, saying that it's already installed. (Incidentally, the WinFsp FAQ contains old info, as the MS link no longer works, and the referenced patch has since been superseded.)

That aside, why does the driver include a SHA1 sig? Windows doesn't support SHA1 sigs at all, so why not remove it?

**Comment by billziss-gh** [comment]
Thanks for the detailed information. I am beginning to wonder whether Microsoft either explicitly disallows or otherwise gets confused by the SHA-1 signature in older OS'es (likely due to some issued update as you say). I will look into removing it for the next release.

> [Edit 2] > corrected signtool query:

It is curious that the output shows that the SHA1 signature is recognized, but not the (also included) SHA-256 signature.

**Comment by billziss-gh** [comment]
I have found this, which says that Windows updates are now issued signed with SHA-256 exclusively. Perhaps as part of this change SHA1 has been completely outlawed?

From https://support.microsoft.com/en-us/topic/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus-64d1c82d-31ee-c273-3930-69a4cde8e64f

> To help protect the security of the Windows operating system, updates were previously signed (using both the SHA-1 and SHA-2 hash algorithms). The signatures are used to authenticate that the updates come directly from Microsoft and were not tampered with during delivery. Because of weaknesses in the SHA-1 algorithm and to align to industry standards, we have changed the signing of Windows updates to use the more secure SHA-2 algorithm exclusively. This change was done in phases starting in April 2019 through September 2019 to allow for smooth migration (see the "Product update schedule" section for more details on the changes).

The article mentions [KB4474419](https://support.microsoft.com/help/4474419) and [KB4490628](https://support.microsoft.com/help/4490628) which are installed on your system.

**Comment by Hub-O-Gits** [comment]
Some additional info that may help narrow down the issue:

I tested older versions of WinFsp, starting from v1.9.21096 (what I previously had installed), and found that everything up to v1.11.22176 install without the signature error pop-up per my OP. (And also successfully map a connection to "\\memfs64\share".) So it appears that it's just the v1.12 series, starting with v1.12.22242, that err out.

**Comment by billziss-gh** [comment]
Please try the following build, which has been signed with SHA-256 only.

[winfsp-1.12.22335.zip](https://github.com/winfsp/winfsp/files/10131997/winfsp-1.12.22335.zip)

(Posting as ZIP file containing the MSI because of GitHub restrictions on files that can be posted.)

**Comment by Hub-O-Gits** [comment]
The first build you posted produced the same error, but the second build did not! Further testing may be necessary to confirm it, but so far, it appears to be working fine. (E.g. I was able to map a network drive to \\\memfs64\share.)

I'll follow up with more info/detail later, but for now, I've attached the diagnostic output for each build below - as installed on a clean (no prior installation of WinFsp) Windows 7 SP1 x64 ESU (Extended Security Updates) virtual machine:

v1.12.22335 b1 = [diag_bat_b1.txt](https://github.com/winfsp/winfsp/files/10134212/diag_bat_b1.txt)
v1.12.22335 b2 = [diag_bat_b2.txt](https://github.com/winfsp/winfsp/files/10134210/diag_bat_b2.txt)

By the way, I wonder if I could see the diag.bat output from your own W7 VM? Unless you don't have ready access to it - I'm just curious to examine the differences with mine (especially the MS patches), since the original driver works on your system.

PS: In case I don't get the chance to say so later, much thanks for taking on the issue. WinFsp is killer software, and I'm grateful to be able to use it.

**Comment by billziss-gh** [comment]
Fantastic news! I will await confirmation from the other thread and if it works I will post as an official release.

----

Here is the `systeminfo` output from the Win7 VM I used earlier. The [KB4474419](https://support.microsoft.com/help/4474419) patch is missing, which may explain why my Win7 VM was working.

[systeminfo.txt](https://github.com/winfsp/winfsp/files/10134551/systeminfo.txt)

(Usually I keep my VM's offline, but I had to put this one online to post the `systeminfo` output. As I was doing this the VM started to do some Windows update. I don't think I ever pressed STOP on the vmconnect window faster 🤣 )

**Comment by Hub-O-Gits** [comment]
> The KB4474419 patch is missing, which may explain why my Win7 VM was working.

I suspect as much as well. It appears that there's just a few Win 7 (and Server 2008?) patches relating to SHA2 & driver signing, and I'd wager that at least one of them essentially functions to further sunset Win 7, thereby forcing the user to upgrade to >= Win 8/10. I had considered uninstalling KB4474419 on my test VM to find out what happens if I then install >= WinFsp v1.12, but with your alternate winfsp-x64.sys driver, it would be academic.

By the way, I've started testing your WinFsp v2.0.22327 beta, so I was wondering if you'll be issuing a driver update to that as well?

Side note: It appears that there's quite a difference in patches between our respective Win 7 VMs:
[VM diff - Bill vs Hub.txt](https://github.com/winfsp/winfsp/files/10137665/VM.diff.-.Bill.vs.Hub.txt)

**Comment by billziss-gh** [comment]
@Hub-O-Gits it would be very helpful if you also tried this build, which I intend to release officially:

[winfsp-1.12.22339.zip](https://github.com/winfsp/winfsp/files/10154832/winfsp-1.12.22339.zip)

(Unfortunately the process that produced the previous build had a major problem in that the assets it produced could be used for public releases, but not for my own development/testing! I have now updated the build process to support both local development/testing, but also produce assets that can be used on older OS'es.)

> By the way, I've started testing your WinFsp v2.0.22327 beta, so I was wondering if you'll be issuing a driver update to that as well?

Yes. If this works I will use the new signing method for the v2.x series of releases going forward.

**Comment by Hub-O-Gits** [comment]
I can confirm that that build appears to work as well - i.e. there's no error upon installation, and I'm able to map a network drive to \\\memfs64\share. (I'm assuming the only difference lies in the signatures of the 3 files listed below, and that they're functional equivalent otherwise. However if there's any other test I should perform, let me know.)

> winfsp-a64.sys
> winfsp-x64.sys
> winfsp-x86.sys

**Comment by billziss-gh** [comment]
@Hub-O-Gits thank you very much for confirming. I am closing this as the problem has been resolved.
