### ISSUE TITLE
Best way to build winfsp and sshfs, and others on Windows

### ISSUE THREAD

**Issue by lonnietc** [winfsp/winfsp#479]
Hello,

Originally, in the recent past, I had been experimenting with Dokany 2 which builds nicely with Visual Studio solution files as well as building some examples as I need to build up a special application that would have the characteristics of a MergerFS, SSHFS, and EncFS all in a single mountable filesystem. I also need to build this application that will be initially for Windows, but then later be easy to port over to Linux and MacOSX.  

It seems that WinFSP, being FUSE based, may be the best way to go in the long run and my initial cursory Internet search suggests that WinSCP is faster, more mature, and possible more stable than Dokany, so this may be the best way to proceed.

In as much, I am wondering about the best, and simplest way to work with WinSCP.  One concern is that WinSCP seems to reference Cygwin a lot, but having limited experience with that one, I have found that it seems to require a large shim layer dll to be used. 

On the other side, I have used Mingw (x64) and have "TDM-GCC-64" installed and am wondering if that is a good possibility for working with WinFSP and projects?

Additionally, I did notice that in the WinFSP "build" directory that there is a Visual Studio (2015 ??) solution file and I also have VS2022 installed but the WinFSP.sln would need updating as well.

Lastly, I am wondering, in general, how hard it is to port some existing Linux FUSE projects to Windows with WinFSP as I am still considering the MergerFS (sort of like a UnionFS) and EncFS as what I need is a type of MergerFS that allows for SSH (SFTP) remote connections from different SSH (SFTP) servers to be mounted and shown as a union of those mounts in a virtual drive.

Any thoughts?

Appreciate any feedback or suggestions so that I can get started in the best way possible.
Thanks and have a great day

**Comment by lonnietc** [comment]
Thanks for the quick reply on this and I have been able to setup my VS2022 to compile and build winfsp & examples (build/VStudio). I had to install the WDK and a few things and everything seems to work and although not critical, I was not able to get the Wix Installer part working even though I installed the Wix 3 extension in my Visual Studio but for now that is not important.

I think that I will continue to work with a Visual Studio solution while I get the feel for WinFSP more and then a bit later switch over to my MSYS2/Mingw 64-bit environment.

Also, I did send a request over to [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp)  and I think that it has now been accepted, but I did not see a lot of activity happening there although I will post a couple more questions on that forum and we can close this ticket for now.

Thanks so very much and I am looking forward to doing more with WinFSP.

**Comment by lonnietc** [comment]
Just an update on the Forum.

I seem to have access to reply to existing posts but cannot create any new post from what I can see so far.  Is there a mailing list available to subscribe to, or should I post here for new questions in the issues section of the Repo?

**Comment by billziss-gh** [comment]
@lonnietc that's curious about the forum. I have approved your request and you should be able to post there. If you are unable however you can continue posting here or preferrably the [Discussions](https://github.com/winfsp/winfsp/discussions) in this project.

**Comment by billziss-gh** [comment]
> Thanks for the quick reply on this and I have been able to setup my VS2022 to compile and build winfsp & examples (build/VStudio). I had to install the WDK and a few things and everything seems to work and although not critical, I was not able to get the Wix Installer part working even though I installed the Wix 3 extension in my Visual Studio but for now that is not important.

FYI you do not really need the WDK and Wix3 unless you are planning to build WinFsp yourself.

**Comment by lonnietc** [comment]
@billziss-gh Yea, the forum seems strange in that I checked it again this morning and it is the same. I can seem to reply to an existing post but cannot create any new posts. Never saw that before.

Maybe WinFSP will have a mailing list in the future as well, but I will look more into the Discussions section as a better way.

Thanks again and have a great day.
