### ISSUE TITLE
Anyone working on MergerFS port to WinFSP?

### ISSUE THREAD

**Issue by lonnietc** [winfsp/winfsp#480]
Hello All,

I am wondering if there is anyone, or any project that you are aware of that is being done for WinFSP to port over MergerFS (a union type filesystem)?

```
https://github.com/trapexit/mergerfs
```

Not sure of the best way to do it, but I am seeking to have a type of MergerFS that allows for dynamic mapping of SSHFS filesystems from different SSH servers into the same Unioned filesystem.

Currently, I am using Visual Studio 2022 with the basic WinFSP build solution to get a feel for things, but might need to switch over to MSYS2/MinGW (x64) in order to start doing something along these lines.

There may already be something like this somewhere and I wanted to see if there was any information that I could find as I need something similar for a special project that is in development now.

Any help would be appreciated.
Thanks

**Comment by billziss-gh** [comment]
Not sure if it will be of any use to you, but I have built a unionfs-like file system in Golang. It is part of a larger project (HUBFS) and is available [here](https://github.com/winfsp/hubfs/tree/master/src/fs/unionfs).

I have had thoughts of porting this unionfs file system to C and the native WinFsp API, but I have not had time to do any of this.

**Comment by lonnietc** [comment]
Thanks, and I had actually downloaded a copy of the HUBFS but did not get a chance to compile it up because I was trying to determine if I wanted to utilize Golang which I am ok at, or C++ which I have much more skill. I like Golan and it offers many new advantages (especially cross-platform stuff that I will need as well) but just have not developed much with it and that could make things take longer to get into place since this will be part of a much larger project.

I read a bit in the Tutorials on the SSHFS port:

```
https://winfsp.dev/doc/SSHFS-Port-Case-Study/
```

and am now trying to get a feel as to if a MergerFS and EncFS port will be possible and useful since the idea is to get one of each of these running to see that that it can be done (and how hard) after which I was thinking that the new FS would take MergerFS for example and start adding SSHFS and EncFS components into a single new application.

Thanks again and have a great day

**Comment by lonnietc** [comment]
Hello,

I was just wondering a little more about the Go implementation for HUBFS and started to wonder if that version can compile for Windows, Linux, and MacOSX as I know that Go is great for cross platform work, and if that is the case then just maybe Golang is more of what I need for this effort but wanted to check all possible options before settling in on one.

To that end, I have also been exploring Dokany as well, but it mostly seems like it is mainly just for Windows.

**Comment by lonnietc** [comment]
Actually, I was just reading more on the HUBFS site and it does, in fact, support cross-platform work.

Maybe I will give it a try as well and see. Perhaps if all goes well then it might not be too hard to work on a unionfs (mergerfs) version from Go and add in the SSH stuff that I need.

Anyway, thanks again for your help.

**Comment by billziss-gh** [comment]
If you are happy with FUSE and do not need Windows file system features, I recommend Go for cross-platform file system development.

**Comment by lonnietc** [comment]
@billziss-gh  Hello and hope that your day is going well 

I was just experimenting with your CGOFUSE and was able to compile the memfs.exe which seemed to build nicely.

One thing that I was wondering was that after it compiled, I started it up with no CLI parameters and it mounted a default "Y:" drive, but showed up as "0 bytes free of 0".

Do I need to specify some default size or something?

On a side note, I was also wondering if you might be interested in working on a SSF filesystem version in Go since I am liking the Golang side of things more and more with WinFSP.  If I can compile and build up your HUBFS and figure out an SSHFS (Golang version) with multiple mounts, then this might be the way to proceed as it could pay off in the long run when I need to go cross platform later.

Any thoughts on these things?
Cheers and have a great day

**Comment by billziss-gh** [comment]
I think cgofuse memfs does not implement `statvfs`, which is why it reports 0 bytes on the volume.

**Comment by lonnietc** [comment]
@billziss-gh Actually it is not only reporting 0 bytes, but it will also not let me put any files in the drive

![image](https://user-images.githubusercontent.com/15264930/209341387-d0b8e59f-e181-4c3f-b76d-e3d3c8fae8f4.png)

**Comment by lonnietc** [comment]
Also, maybe we should move this over to the CGOFUSE Repo issues if that is a better place for this discussion but it is up to you.

```
https://github.com/winfsp/cgofuse
```

I was going to try and compile the Go HUBFS version today as well to see it in action from the source code compile since I want to learn what the purpose of the Union filesystem code in that one since you mentioned it to me and I want to find out if that allows HUBFS to mount multiple Github repos and union them, or something as well.

Truly appreciate you looking into these things and helping since I tend to feel more confident that the WinFSP Go CGO approach is what I am probably looking for to do what I need.

**Comment by lonnietc** [comment]
Quick update.

The good news is that if I run the memfs.exe created in C++ by WinFSP then that one works as expected and allows me to put files in it.

This leads me to believe that there is something amiss with the Go layer.
