### ISSUE TITLE
Mountpoints A and B breaks Windows deployment components with 0x80070057

### ISSUE THREAD

**Issue by ferferga** [winfsp/winfsp#482]
## Bug Report

*DISCLAIMER: I'm not sure if this is a WinFSP problem or not, as I don't have any SMB share I could test with, only rclone remotes, but hopefully I can get some help here as Microsoft doesn't seem to care about my Feedback Hub feedback and I want to make sure this issue is not from WinFSP before trying to push the issue further with them.*

When using ``rclone mount`` or SSHFS-Win (this is why I'm posting this here and not at rclone's), no matter if using the ``--network-mode`` argument (which mounts as a network share) or not (which mounts as a fixed drive) and either the A: or B: mountpoints, common operations accross Windows like:

* Installing windows updates from Windows Update (security definitions and **some** .NET framework updates succeeed).
* Upgrading Windows versions, like from 10 to 11, but also from 11 22H1 to 22H2
* Installing Microsoft Store apps
* Use DISM or SFC

Fail with 0x80070057 error code.

### How to Reproduce

* Mount anything in A: or B: mountpoints
* Search for updates in Windows Update, install something from Microsoft Store or deploy an appx, among others.
* See how all these operations fail with error code 0x80070057

### Behaviors

The system should not be affected at all by the used mountpoints

### Additional context

I think this issue might have its root case in the fact that, historically, those mountpoints were used for floppy disks and some Windows code expects floppy disk readers to be at A: or B:, which makes modern code "crazy" as nobody use floppy disks nowadays.

Although I'm using the beta, I've been experiencing this issue for a few years (since rclone released compatibility with Windows in its mount command). At first I thought my Windows installation was broken, but after a lot of reimaging, dism repairs, etc... I found that deactivating those mountpoints fixed all the issues. **I'm saying this because the fact that I'm using WinFSP 2023.Beta1 probably doesn't change a thing**

### Environment

- OS version and build: 10.0.22621.963
- WinFsp version and build: WinFSP 2023.Beta1

**Comment by Masamune3210** [comment]
This likely isnt somethng that winfsp can really do anything about. As you kinda walked upon, Windows has some pretty ancient code and a lot of the system still assigns importance to A: and B:

**Comment by billziss-gh** [comment]
> I think this issue might have its root case in the fact that, historically, those mountpoints were used for floppy disks and some Windows code expects floppy disk readers to be at A: or B:, which makes modern code "crazy" as nobody use floppy disks nowadays.

I am fairly certain that Windows does indeed have special behavior for drives `A:` and `B:` and that in general they should not be used as mountpoints for WinFsp.

For this reason I am finding it hard to recognize this as a WinFsp bug and I am uncertain what could be done about it, if anything:

- One solution would be to disallow mounting on drives `A:` and `B:` from WinFsp. But there may be legitimate reasons that someone wants to mount on these drives regardless of the other problems experienced.

- Another solution would be to provide better emulation of a "floppy" drive when someone mounts on these mountpoints. But this sounds like a lot of work for little reward and might not be even generally feasible with the kind of file systems that WinFsp enables.

**Comment by ferferga** [comment]
Hello, just a heads up for whoever stumbles across this issue.

For me it seems like it's been resolved in Windows 11 22621.2428 (after the release of 23H2 the 26 of September of 2023).
