### ISSUE TITLE
Download link of web page points to Winfsp 2022.2 not WinFsp 2022.2 Update1

### ISSUE THREAD

**Issue by infeo** [winfsp/winfsp#495]
## Bug Report

When a user downloads WinFsp from the homepage (https://winfsp.dev/rel/), not the latest stable release is downloaded but yeah, well, one revision number earlier.

Although, they are codewise equal, the update prevents a blue screen on devices running certian software, see https://github.com/winfsp/winfsp/issues/492. It would be nice that users do not stumble into this.

### How to Reproduce

Click download button for WinFsp.

### Behaviors

**Expected:** WinFsp 2022.2 Update1 is downloaded
**Actual:** Winfsp 2022.2 is downloaded.

**Comment by billziss-gh** [comment]
Website updated. Thanks!
