### ISSUE TITLE
Is NormalizedName a filename or the full path?

### ISSUE THREAD

**Issue by hach-que** [winfsp/winfsp#497]
## Question

It's not super clear whether this parameter is supposed to be the full path, or just the filename of the file node.

For example, in the WinFsp .NET MEMFS example:

- For `CreateEx`, it's the full value of `FileNode.FileName`: https://github.com/winfsp/winfsp/blob/master/tst/memfs-dotnet/Program.cs#L428
- For `Open`, it's the full value of `FileNode.FileName`: https://github.com/winfsp/winfsp/blob/master/tst/memfs-dotnet/Program.cs#L473
- For `GetDirInfoByName` it's the value of `Path.GetFileName(FileNode.FileName)` (effectively basename of a path): https://github.com/winfsp/winfsp/blob/master/tst/memfs-dotnet/Program.cs#L1124

My initial attempt at setting NormalizedName to just the filename of the file (and not the path) seemed to result in I/O errors from applications, so I'm *suspecting* it needs to be the full path. I checked/read the docs but it wasn't super clear though, so clarity on this parameter would be appreciated.

**Comment by hach-que** [comment]
Ok, having had a chance to do some testing, it does look like this parameter wants a full path name in the form of `\Path\To\File.txt`. Seems like `GetDirInfoByName` is also fine with full paths, so not sure why the MEMFS example is calling `Path.GetFileName`.

**Comment by billziss-gh** [comment]
It needs to be the full path.

For `GetDirInfoByName` it should be the file name only (no path), because directory information does not include path information.

You must pass enable [`PassQueryDirectoryFileName`](https://github.com/winfsp/winfsp/blob/master/src/dotnet/FileSystemHost.cs#L290) for `GetDirInfoByName` to work.

**Comment by hach-que** [comment]
Thanks for the clarification.
