### ISSUE TITLE
 No MSFT_Volume objects found with property 'DriveLetter' equal to 'Z'

### ISSUE THREAD

**Issue by rakobrady** [winfsp/winfsp#507]
## Bug Report

_Provide a descriptive title and a detailed explanation of the problem you are experiencing. Ensure that your issue has not been filed before._

After I mount a volume and issue a `Get-Volume` command. I get the error message `No MSFT_Volume objects found with property 'DriveLetter' equal to 'Z'`

I would expect WinFsp to create a volume that can be seen by powershell. 

### How to Reproduce

_Provide detailed information on how to reproduce the problem._

1. Mount winfsp volume with `Z:` or `\\.\Z:` 
2. `Get-Volume Z` in Powershell

### Behaviors

_Provide information on the expected and actual behaviors._

Expected, powershell would see the volume
Actual, `No MSFT_Volume objects found with property 'DriveLetter' equal to 'Z'`

### Environment

- OS version and build: Windows Server 2022 Datacenter 21H2 20348.1249
- WinFsp version and build:  v1.12.22339

**Comment by billziss-gh** [comment]
I believe `Get-Volume` is used to enumerate "disks/partitions" and not file systems. WinFsp only implements file systems without an underlying "disk".

For example, on my laptop `Get-Volume` lists all partitions:

```
billziss@xps ⟩ ~ ⟩ get-volume

DriveLetter FriendlyName FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining Size
----------- ------------ -------------- --------- ------------ ----------------- ------------- ----
            Recovery     NTFS           Fixed     Healthy      OK                       515 MB ...B
C                        NTFS           Fixed     Healthy      OK                      1.08 TB ...B
                         NTFS           Fixed     Healthy      OK                      85.1 MB ...B
```

**Comment by rakobrady** [comment]
Is it possible to configure WinFsp's file system to be enumerated under this command?

I am also using applications such as Adobe Premiere, and the WinFsp filesystem does not show up under that application's explorer (where the C drive is visible). I assumed that the two were related and `Get-Volume` was a simpler way to investigate.

**Comment by rakobrady** [comment]
Isn't `Get-Disk` used to enumerate disks?

**Comment by billziss-gh** [comment]
Which Adobe application does not work with WinFsp? Can you demonstrate the problem with Adobe against MEMFS?

Also try mounting as a network file system (e.g. using the `-u \Server\Path` switch in MEMFS).

**Comment by rakobrady** [comment]
The Adobe Premiere application, for instance, does not see the disk file system. 

Interestingly, the disk filesystem **is** recognized when running `passthrough-dotnet`. I will continue to dive into any differences in our implementation and the passthrough implementation, but I did notice that `passthrough-dotnet` uses the WinFsp Launcher.

Does the choice to use the WinFsp launcher or not influence this behavior? 

Regarding switching to a network drive mount: If I mount as a network drive the application can see the file system, but for many other reasons (Mainly around compatibility with network drives) it is not a viable option for us to mount as a network file system. We need to present the filesystem as a local disk.

**Comment by billziss-gh** [comment]
> The Adobe Premiere application, for instance, does not see the disk file system.

Does this problem happen with MEMFS? MEMFS is the reference file system for WinFsp, so if you can demonstrate a bug against MEMFS there is a much higher chance of getting it fixed.

> Does the choice to use the WinFsp launcher or not influence this behavior?

The Launcher starts file systems as network drives by default, so it is likely why this worked.

**Comment by rakobrady** [comment]
>Does this problem happen with MEMFS? MEMFS is the reference file system for WinFsp, so if you can demonstrate a bug against MEMFS there is a much higher chance of getting it fixed.

Yes, the problems happens with memfs-dotnet but not with passthrough-dotnet.
