### ISSUE TITLE
Create drive as a global drive failed with winfsp memfs-fuse sample

### ISSUE THREAD

**Issue by jack2007** [winfsp/winfsp#535]
## Bug Report

Hi, I'm trying winfsp memfs-fuse sample.
memfs-fuse-x64.exe T:           I can get a network share drive.

When I'm trying to create a global drive using \\.\ syntax, I get an error.
memfs-fuse-x64.exe \\.\T:
Cannot set WinFsp-FUSE file system mount point.
The service memfs-fuse-x64 has failed to start (Status=c0000022).

### How to Reproduce
As above

### Behaviors
How can I create a global drive with winfsp-fuse?

### Environment

- OS version and build: 10.0.19045.3803
- WinFsp version and build: winfsp-2.0.23075

**Comment by billziss-gh** [comment]
You need to be administrator to use the `\\.\X:` syntax.
