### ISSUE TITLE
WinFsp Installer improvements

### ISSUE THREAD

**Issue by billziss-gh** [winfsp/winfsp#54]
This issue tracks a few installer improvements:

- [x] The installer does not currently support major upgrades. The main reason for this is that if the FSD is loaded, it cannot be unloaded and upgraded without a reboot. Investigate whether it is possible to rectify this.

- [x] The installer should check that it is being installed on Windows 7 or higher. [WinFsp uses Vista DDI's and API's, but is only being tested on Win7 or higher.] Relevant link: http://stackoverflow.com/a/2733980

- [ ] The installer should check whether the Microsoft Security Advisory 3033929 is installed (if the OS is Windows 7). See issue #43. Relevant link: http://stackoverflow.com/a/29946122

**Comment by lithiumFlower** [comment]
I'm curious, are there any plans to tackle the first item in the near future?

**Comment by billziss-gh** [comment]
@lithiumFlower 

It is a hard item to fix. The main reason is that the driver cannot be unloaded (once loaded) and to safely perform the upgrade requires a reboot. Properly building the installer to do this and test all installation scenarios is beyond my Wix skills.

I will happily accept a PR that addresses this issue from someone that understands Wix better than me.

**Comment by lithiumFlower** [comment]
Ok, good to know. Btw I've been using winfsp for almost a year now and I have to say I'm impressed! Solid software.

**Comment by fsgeek** [comment]
File systems do not fit into the WDM driver model. They are not enumerated on the root bus and are loaded as NT 4.0 kernel mode (legacy) drivers. Physical file systems may monitor PnP requests for device removal (see FastFat code for that) but they do not have PDOs and FDOs. They do not use a direct attachment model but rely upon a special structure (volume parameter block) for managing the association between media and file system volume instance.

**Comment by billziss-gh** [comment]
This functionality has been implemented and is currently in the private branch [`pvt-sxs`](https://github.com/winfsp/winfsp/tree/pvt-sxs). It will not be in the next release (`v1.12` - WinFsp 2022.2) but it will appear in the release after the next (`v2.0` - WinFsp 2023).
