### ISSUE TITLE
FileName Obfuscate

### ISSUE THREAD

**Issue by jgh0721** [winfsp/winfsp#540]
I'm creating a virtual drive using the WinFSP driver and obfuscating the filename to show it. 

This means that to the user, the path Z:\a\b\c.txt is mapped to a random string C:\Sandbox\wqrfsd\ewfdwesd\rewrwerwe when it is actually stored physically. 

The implementation is based on an example called ntptfs, and the CreateFile callback returns success (any internal NtCreateFile or NtOpenFile etc. will be successful), but ultimately Windows returns a 123 (ERROR_INVALID_NAME) error.  

Are there any examples, etc. of how to obfuscate filenames in WinFSP?

**Comment by billziss-gh** [comment]
Your obfuscation scheme must produce valid file names in Windows. Read about valid file names in Windows here: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
