### ISSUE TITLE
Please include also `memfs-fuse3` *binaries* in the developer installer

### ISSUE THREAD

**Issue by sschuberth** [winfsp/winfsp#545]
## Enhancement Request

In order to try reproducing https://github.com/cryptomator/cryptomator/issues/3173 with stand-alone WinFsp, it would be great in the developer option for the installer would not only provide `memfs`, but also `memfs-fuse3`.

**Comment by billziss-gh** [comment]
The memfs-fuse3 sample is included in the installer. You can find it under the `\Program Files (x86)\WinFsp\samples\memfs-fuse3` directory after enabling the developer option.

**Comment by sschuberth** [comment]
> The memfs-fuse3 sample is included in the installer.

Sorry, I was referring to the *binary*, so I could easily use it for testing e.g. via `net use X: \\memfs-fuse3\test`, out of the box. I'm not a C developer, but want to help to narrow down the root cause of [this issue](https://github.com/cryptomator/cryptomator/issues/3173).

**Comment by billziss-gh** [comment]
The purpose of the provided samples is to be used as guidance for developers to build their own file systems. Many of them are not generally useful and including their binaries in the installer would clutter the WinFsp installation for everyone, even if including them might be useful for some people.

My apologies, but given the above I do not think I will be adding those binaries to the installer.

**Comment by sschuberth** [comment]
> My apologies, but given the above I do not think I will be adding those binaries to the installer.

Ok. Sorry for becoming slightly off-topic then, but could you give some guidance how to narrow down the linked issue then as a non-C developer?
