### ISSUE TITLE
Windows try to open files, even they are marked FileAttributes.Offline for preview

### ISSUE THREAD

**Issue by uhrb** [winfsp/winfsp#548]
## Question

Hi!
I am implementing remote file system using WinFsp. Everything more or less goes well. Thank you for such interesting and powerful tool!
I have a question related to regarding the Windows behavior. Quite tricky I would say.
When my file system is mounted, sometimes windows trying to open particular files for reading (especially images) even they marked with FileAttributes.Offline. Is it way to alternate this behavior from file system side, to prevent Windows open files for preview which are Offline, and only issue Open request when file operation requested (such as open for copy, etc.)?

Thansk!
+=UH

**Comment by billziss-gh** [comment]
Any operation on a file in Windows will result in the file being opened. For example, an innocuous `GetFileAttributes` can result in the file being opened. This is by Windows file system design.

Explorer is smarter and in general tries to avoid opening files unnecessarily. For example, a file's attributes can also be retrieved from the directory listing.

Nevertheless Explorer will open files for other reasons, such as preview, etc. The only way I know to diminish this is to start your file system as a network driver rather than a local drive.

**Comment by uhrb** [comment]
Hi! Something I expected to hear, thank you for confirmation.
Could you please point me, how to mount as network drive? Is there any special parameters for FileSystemHost or Mount method I can specify?

**Comment by billziss-gh** [comment]
Are you using .NET? Then it should be as simple as using the `Prefix` property on the `FileSystemHost`.

For example, if you want your prefix to be `\\MYFS\MYNAME` set the `Prefix` to `\MYFS\MYNAME` (notice the single backslash in the `Prefix`).

**Comment by uhrb** [comment]
Thanks! It helps a little bit - Windows 11 does not try to open them, if they are on network drive and marked offline, until actual file operation is fired. However, even on network drive, if file have Normal attribute, it tries to open it. 
I think more or less it make sense. In any case, I think I can achieve necessary behavior with your hint. 
Thanks a lot! And one more time thank you for your work!

**Comment by uhrb** [comment]
Additional comment for future generations:
When windows file explorer try to pull some information about properties of the file (right click on the file-> properties) on network drives, it may try to open file anyway (for example, for me it happened for EXE files). But in this case, at least in situations when file marked with Offline attribute, it also sends FILE_SYNCHRONOUS_IO_NONALERT in CreateOptions. If reply with STATUS_FILE_IS_OFFLINE - it doesn`t call Read operations on file, and properties opened immediately, so based on CreateOptions FS can differentiate behavior.
