### ISSUE TITLE
Concurrency during asynchronous Read and Write operations

### ISSUE THREAD

**Issue by uhrb** [winfsp/winfsp#549]
Hi! I have a question regarding asynchronous operations Read and Write. As I can see, these functions can return STATUS_PENDING, to indicate that operation is undergoing, and at the end of the operation custom FS can notify host about operation results using operation hint, obtained during initial context. However, I am unsure what the behavior is, when STATUS_SUCCESS reported with hint by different thread before the actual return to the FSP core. Here the hypothetic scenario in pseudo-C#: 

Imagine following implementation of Read operation:
```
var hint = _host.GetOperationRequestHint();
Task.Run(() => {
  ...
 _host._host.SendReadResponse(hint,  STATUS_SUCCESS, actualBytesTransfered);
}).ConfigureAwait(false);
...somecode...
return STATUS_PENDING;
```
Since Task with reporting STATUS_SUCCESS is run in different context, it can be executed right away, and even faster, than return from Read operation happens or STATUS_PENDING is processed by WinFsp (for example, something heavy happens on `...somecode...` )
Unfortunately, my C-skills are quite outdated, and I can't figure out what is the behavior of WinFsp from the code in such situations by myself. 
Is there any way to figure out that status of STATUS_PENDING was committed before committing STATUS_SUCCESS?

**Comment by billziss-gh** [comment]
I have not looked into this code in some time, but from looking into the code that handles `STATUS_PENDING` just now, it looks to me that things will work correctly regardless of the order that the `STATUS_PENDING` is handled vs the task that sends the asynchronous response.

See:
https://github.com/winfsp/winfsp/blob/v2.0/src/dll/fs.c#L337-L338

Basically the main loop of the file system dispatcher ignores the response from the user mode file system when it receives `STATUS_PENDING`, so it should be safe if the response has already been sent asynchronously.
