### ISSUE TITLE
[FUSE API] Add getpath to fuse3

### ISSUE THREAD

**Issue by Calorado** [winfsp/winfsp#550]
This would also include all the osxfuse functions. Currently they are only available for the fuse2 api. Is there a reason for this, or is it just a mistake?

**Comment by billziss-gh** [comment]
Historically different FUSE implementations have added new operations to the FUSE2 API. So it was easy to justify adding such operations to the WinFsp FUSE2 implementation as well.

When the WinFsp FUSE3 implementation was added the only other FUSE3 implementation was the reference one from libfuse and it made less sense to break compatibility with it.

**Comment by Calorado** [comment]
I understand.
