### ISSUE TITLE
how to make a drive using memfs

### ISSUE THREAD

**Issue by megalosVigneswaran** [winfsp/winfsp#555]
## how to create drive using memfs?

i want to create a drive using memfs . i want create a symlink in my memfs drive and for example i create a symlink if i go to property that will only shows the symlink properties . but i want to show the the orginal file's property.

Please help to do that.

and i tried to use the command `` memfs-x64.exe -m Z``  in power shell ( as admin privilege ) the output is : ``memfs -t -1 -n 1024 -s 16777216 -m Z``
The service memfs has started. but i cant see any drive in my explorer

I kindly request , please help me.

I am beginner to winfsp 

and where can i get the document of this command . I am suffered  a lot i can`t find the straight forward documents.

![memfs](https://github.com/winfsp/winfsp/assets/134774303/ce8cce8b-86c8-478c-af56-579c9f75712d)

![no drive](https://github.com/winfsp/winfsp/assets/134774303/1ee8c773-4a74-40ad-b964-985a77709987)

**Comment by billziss-gh** [comment]
Try `memfs -m Z:` (notice the colon `:` after the drive letter). Make sure that you do not create a drive from an Administrator prompt (otherwise the new drive `Z:` will not be visible from Explorer).
