### ISSUE TITLE
manual install not use msi file please help

### ISSUE THREAD

**Issue by amidevous** [winfsp/winfsp#562]
manual install not use msi file please help

please can you tell me how to install winfsp

without using the msi file

it would be to use with wimpe and rclone

only msiexec and we can not install msi in wimpe

i tried to copy the contents of the program file folder

apparently it is not enough

i think that must be missing the registry keys without doubt

actual found folder copied C:\winpe_amd64\mount\Program Files (x86)\WinFsp

not work

Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed

thanks in advance for your help

**Comment by amidevous** [comment]
please answer and provide the necessary instructions

for a manual installation without using the msi file

it's been several days since you made this request

it's your project so you must know the answer

and it should not take you only a few seconds to give it

it is therefore abnormal that after several days

you still have not answered by providing the requested elements

thank you in advance

**Comment by NiKiZe** [comment]
> please answer and provide the necessary instructions
> 
> for a manual installation without using the msi file
> 
> it's been several days since you made this request
> 
> it's your project so you must know the answer
> 
> and it should not take you only a few seconds to give it
> 
> it is therefore abnormal that after several days
> 
> you still have not answered by providing the requested elements
> 
> thank you in advance

How much have you paid for this software or support?
If 0 then it is abnormal for anyone to make the kind of demand you are making, and especially with that kind of tone.

**Comment by amidevous** [comment]
and you've finished answering on all the projects and especially beside the point without even testing what is given as information indication or configuration

you think you're on a community forum or what

you're on github here dude the requests are addressed to the developer of the projects

if you're not the developer of the project you don't have to answer them

especially to answer beside the point and exasperate and annoy people like you've been doing since yesterday

in addition without even taking the time to try and test the information that is transmitted

you haven't even published a single commit on this project

it's the same for the winboot project

you haven't published a commit and you allow yourself to answer

here you're on github the only reason why github allows

other users to participate in the issue

it's on 2 conditions

either you encounter the same problem and you can provide additional details that can allow the developer to resolve the problem

either you tested the problem you found a solution that you were able to validate as being functional there you do neither one nor the other and those since yesterday

your place is absolutely not on github but in a community support forum

so please stop writing on github issues and go to a community forum thank you

in addition you say what did I pay

we are on an open source project for your information

which means that the installer code must also be available

if this is not the case like here it is perfectly normal and justified to ask for it

**Comment by NiKiZe** [comment]
I didn't even notice at first that you are the same guy/girl as https://github.com/ipxe/wimboot/issues/53 but the attitude is totally the same, respectless behaviour, you don't have the right to demand anything from anyone unless you have actually paid for it, and that goes for any project or software you use. Asking is one thing, and your first post here was fine, your follow up was totally out of line.

This got me thinking of https://github.com/bradfitz/issue-tracker-behaviors

**Comment by billziss-gh** [comment]
@amidevous please make sure that you are using the WinFsp software according to its license:

https://github.com/winfsp/winfsp/blob/master/License.txt

WinFsp can work under WinPE, although it is not a supported scenario. You will have to figure things out on your own. I have a script that shows how to install WinFsp in a WinPE environment that may be of help. However I have not tested it with WinFsp version 2 (only with 1.x versions).

https://github.com/winfsp/winfsp/blob/master/tools/winfsp-winpe.bat

Lastly, this is an open source project and no one owes you any help. Please remember this in your discussions.
