### ISSUE TITLE
How to Hide Linux Hidden Files (Starting with .) in Windows 11 File Explorer via WinFsp.

### ISSUE THREAD

**Issue by hongyi-zhao** [winfsp/winfsp#563]
Hi,

I am currently using WinFsp to mount my Linux home directory as a virtual drive (Z:) in Windows 11 running in qemu/kvm. I noticed that all hidden files from Linux (files starting with a dot, e.g., .bashrc) are visible in Windows File Explorer. I would like to configure WinFsp or Windows File Explorer to hide these files.

Is there a recommended way to configure WinFsp or Windows File Explorer to hide Linux hidden files? Any guidance or suggestions would be greatly appreciated.

Thank you!

Regards,
Zhao

**Comment by billziss-gh** [comment]
The regular WinFsp-FUSE layer provides a command line switch `-o dothidden` that adds the hidden attribute to such files, so that they do not normally appear in File Explorer. I am unsure if this option is surfaced by the file system you are using.
