### ISSUE TITLE
Passthrough with 512+ threaded file access fails with CRT (Windows 10)

### ISSUE THREAD

**Issue by ShawnMcGrathEpic** [winfsp/winfsp#566]
## Bug Report

Using Win32's CRT fopen on 512+ threads causes fopen() to fail on the 512th call.  CreateFile() works, CRT works on non-WinFsp paths.

### How to Reproduce

Run passthrough with the following args: -p D:\devel\wsfs_syn\1 -m k:

Test program creates 512 threads.  Each thread creates a file in the mount point, writes its path to the file, then closes the file.  The test program can either be run using the CRT's fopen() or Win32's CreateFile().  CreateFile() always works, CRT fails to fopen() on the 512th file.  If the file path is NOT a WinFSP drive everything works fine in both CRT and Win32.  If NUM_THREADS is 511 everything works, 512 breaks threadFnCRT only.

```

#define NUM_THREADS 512

#include <Windows.h>
#include <stdio.h>

static volatile long file_id;
static volatile long num_files_writen;

DWORD threadFnCRT(void *args) {
	int fid = InterlockedIncrement(&file_id);
	char buff[1024];
	int len = snprintf(buff, sizeof(buff), "K:\\%d.txt", file_id);
	FILE *file = fopen(buff, "w");
	fwrite(buff, len, 1, file);
	fclose(file);
	InterlockedIncrement(&num_files_writen);
	return 0;
}

DWORD threadFnWin32(void *args) {
	int fid = InterlockedIncrement(&file_id);
	char buff[1024];
	int len = snprintf(buff, sizeof(buff), "K:\\%d.txt", file_id);

	HANDLE h = CreateFileA(buff, GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
	WriteFile(h, buff, len, NULL, NULL);
	CloseHandle(h);
	InterlockedIncrement(&num_files_writen);
	return 0;
}

int main(int argc, char **argv) {
	HANDLE thread_handles[NUM_THREADS];
	for (int i = 0; i < NUM_THREADS; ++i) {
		thread_handles[i] = CreateThread(0, 0, threadFnCRT, NULL, 0, 0);
	}
	while (num_files_writen < NUM_THREADS) {
		Sleep(1);
	}
	return 0;
}

```

### Behaviors

fopen() fails on the 512th thread.  It shouldn't.

### Environment

- Microsoft Windows [Version 10.0.19045.4651]
- WinFsp version 2.0.23075.

**Comment by ShawnMcGrathEpic** [comment]
I added _setmaxstdio(8192); and it now stops working at 1024 threads instead of 512.  I imagine the issue is just the overhead of passthrough holding on to handles longer than straight through to an ntfs volume?

**Comment by billziss-gh** [comment]
Apologies for the late response as I just returned from vacation.

According to the documentation of [`_setmaxstdio`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170) the default stdio handle limit is 512.

This would suggest that things work correctly. This however does not explain:

- Why the same program is able to open more stdio handles when running against a non-WinFsp file system.
- Why the program is able to open 1024 handles after doing `_setmaxstdio(8192)` (it should be able to open 8192 handles).

May I also suggest that you use `_beginthreadex` to start your threads when you use the CRT and that you check any errors returned from `fopen` and `CreateFileA`? This would let us better understand the problem and ensure that what we are observing is not a consequence of a race condition. (E.g. are you using the multi-threaded CRT in your experiments?)
