### ISSUE TITLE
File watchers doesn't detect file additions in a WinFSP directory

### ISSUE THREAD

**Issue by felipecrs** [winfsp/winfsp#571]
## Bug Report

I initially opened this in rclone, but turns out this behavior comes from WinFSP:

- https://github.com/rclone/rclone/issues/7985

A demonstration:

```
npm i chokidar

node -e "require('chokidar').watch('C:\\Users\\felip\\clipboard-sync').on('all', (event, path) => { console.log(event, path); });"
```

https://github.com/user-attachments/assets/805cf6d2-e43b-4a59-957f-099a96160534

### How to Reproduce

Read above.

### Behaviors

I would expect the file watchers to trigger on events, at least when explorer is refreshed.

### Environment

- OS version and build: Windows 11 23H2
- WinFsp version and build: 2.0.23075

**Comment by billziss-gh** [comment]
Apologies for the late response as I just returned from vacation.

How are the files added into the local file system: are they added via the local file system API's (i.e. by a program that runs on the local kernel on your computer) or are they added in the remote file system directly (i.e. by a program that runs on a remote computer and never interacts with the local kernel on your computer)?

If the latter then you will not receive file system notifications. By default WinFsp reports notifications for file system operations that happen via the local kernel, because it cannot know about files that are added remotely.

WinFsp does have an API that allows a file system such as rclone to report notifications for remote operations, but I do not believe that rclone currently uses it.

**Comment by felipecrs** [comment]
> Apologies for the late response as I just returned from vacation.

No worries at all, thanks for taking the time to answer.

Got it.

In my case, I was testing with both `rclone mount` (and then adding a file through another compute which rclone syncs back to the compute I'm testing) and SSHFS, which is similar, I guess.

> WinFsp does have an API that allows a file system such as rclone to report notifications for remote operations, but I do not believe that rclone currently uses it.

Does it mean the solution would be to implement to report notification mechanism on rclone? /cc @ncw which was participating on the rclone side of the discussion.

I was hoping for a more transparent solution, but I don't know anything.

**Comment by ncw** [comment]
Rclone does have such a mechanism but I don't know how we would communicate those changes to winfsp.

**Comment by billziss-gh** [comment]
@ncw 

It is possible to notify the kernel of remote file changes by using the [`FileSystemHost.Notify`](https://pkg.go.dev/github.com/winfsp/cgofuse/fuse?utm_source=godoc#FileSystemHost.Notify) method. This method accepts the path of the file that has changed and an action that describes how the file was changed:

```go
const (
	NOTIFY_MKDIR    = 0x0001
	NOTIFY_RMDIR    = 0x0002
	NOTIFY_CREATE   = 0x0004
	NOTIFY_UNLINK   = 0x0008
	NOTIFY_CHMOD    = 0x0010
	NOTIFY_CHOWN    = 0x0020
	NOTIFY_UTIME    = 0x0040
	NOTIFY_CHFLAGS  = 0x0080
	NOTIFY_TRUNCATE = 0x0100
)
```

The drawback of using this method is that it allows a single file change to be reported per call. The native WinFsp API ([`FspFileSystemNotify`](https://github.com/winfsp/winfsp/blob/v2.1B1/inc/winfsp/winfsp.h#L1242-L1307)) allows for multiple file changes to be reported per call; unfortunately this is not currently exposed to FUSE and Go.

**Comment by ncw** [comment]
@billziss-gh thanks Bill

Typically rclone will notice a file has been created, removed, or changed somehow. NOTIFY_CREATE for created, NOTIFY_UNLINK for removed, but what would I send for changed ? Maybe unlink then created, or truncated (to show file size has changed)?

I note this is Windows only. Do you know if there is a similar mechanism for Linux/macOS running via libfuse?

**Comment by billziss-gh** [comment]
> Typically rclone will notice a file has been created, removed, or changed somehow. NOTIFY_CREATE for created, NOTIFY_UNLINK for removed, but what would I send for changed ?

Use `NOTIFY_UTIME`.

Although you may not want to send these messages for every file that changed as this could be expensive.

> I note this is Windows only. Do you know if there is a similar mechanism for Linux/macOS running via libfuse?

I have not checked recently, but AFAIK there is no such notification mechanism in libfuse. There is a "notification" mechanism to invalidate kernel caches, but nothing that will push the notifications to applications listening via `inotify`, etc.

**Comment by felipecrs** [comment]
@billziss-gh I guess the conclusion is that there is nothing to be done on WinFSP side. I will close this ticket. Let me know otherwise.

**Comment by billziss-gh** [comment]
@felipecrs I think so. Thanks.
