### ISSUE TITLE
Winget installs the beta package and hangs Windows Explorer

### ISSUE THREAD

**Issue by Mazino-Urek** [winfsp/winfsp#585]
## Bug Report

Updating software through Winget gives this version number:

```
Name             Id                        Version     Available   Source
-------------------------------------------------------------------------
WinFsp 2023      WinFsp.WinFsp             2.0.23075   2.1.24255   winget
```
It is a beta package. By default, it is expected that a stable package will be installed in the system.

### How to Reproduce

Execute the command,

`winget upgrade --all`

### Behaviors

Uninstall the stable version of the software with a beta one.

### Environment

- OS version and build: 

```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
```

- WinFsp version and build:  2.0.23075

**Comment by billziss-gh** [comment]
I do not maintain the winget package for winfsp and therefore I do not enough about this problem. You may want to ask in the winget repo.
