### ISSUE TITLE
BSOD occurrence and 3rd party filter

### ISSUE THREAD

**Issue by zakels** [winfsp/winfsp#587]
## Bug Report
We've got an issue updates from [Issue#578](https://github.com/winfsp/winfsp/issues/578#issue-2523729161).

The issue dealt with, I believe, 3rd party non-standard filter `bmsfile2drv` and we suggested to remove the filter if the issue persists. And our client did so. But we've noticed recently there are a lot more PCs that has the same filter driver installed and it seems like they are causing problem once again.

What we've heard from our client is that he is now experiencing BSOD on daily basis. And luckily, we were able to receive the full dump from our client [Full Dump](https://drive.google.com/file/d/1umITOtqxrrj5672gDIpgV3dC86SO36-K/view?usp=drive_link)

Call site below
```
3: kd> kc
 # Call Site
00 nt!KeBugCheckEx
01 nt!KiBugCheckDispatch
02 nt!KiSystemServiceHandler
03 nt!RtlpExecuteHandlerForException
04 nt!RtlDispatchException
05 nt!KiDispatchException
06 nt!KiExceptionDispatch
07 nt!KiPageFault
08 nt!IopGetFileObjectExtension
09 nt!IoGetOplockFullFoExt
0a nt!FsRtlpOplockDequeueRH
0b nt!FsRtlUninitializeOplock
0c winfsp_x64!FspPosixSetUidMap
0d winfsp_x64!FspPosixSetUidMap
0e winfsp_x64!FspPosixSetUidMap
0f nt!IofCallDriver
10 FLTMGR!FltpLegacyProcessingAfterPreCallbacksCompleted
11 FLTMGR!FltpDispatch
12 nt!IofCallDriver
13 bmsfile2drv
14 bmsfile2drv
15 nt!IofCallDriver
16 nt!IopDeleteFile
17 nt!ObpRemoveObjectRoutine
18 nt!ObfDereferenceObjectWithTag
19 nt!ObCloseHandleTableEntry
1a nt!NtClose
1b nt!KiSystemServiceCopyEnd
1c 0x0
```

### How to Reproduce

Not much detail were provided this time.

### Environment

- OS version and build: OSBUILD(19041), OSSERVICEPACK(3930)
- WinFsp-x64.sys version: 2.1.24051.0

**Comment by billziss-gh** [comment]
Is this a new issue or the same issue as #578? Please do not open multiple issues for the same problem.

I will close this issue and reopen the old one.
